blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.LandingView.as_view(), name='landing_page'),
    path('blog/', views.HomeView.as_view(), name='home'),
    path('info/', views.InfoView.as_view(), name='info'),
    path('post/create-text/', views.TextPostCreateView.as_view(), name='text_post_create'),
    path('post_create_special/', views.MakeSpecialPost.as_view(), name='post_create'),
    path('post/<pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<pk>/<comment_id>/reply/', views.PostChildComment.as_view(), name='replyToComment'),
    path('post/<pk>/update', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<pk>/delete', views.PostDeleteView.as_view(), name='post_delete'),
]

dj02_django_blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dj02_django_blog import settings

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),

    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import UserDetailView, UserListView, UserRedirectView, UserUpdateView, add_follower
from . import views

app_name = 'users'

urlpatterns = [
    path('', view=UserListView.as_view(), name='list'),
    path('~redirect/', view=UserRedirectView.as_view(), name='redirect'),
    path('<str:username>/follow/', views.add_follower, name='follow'),
    path('<str:username>/unfollow/', views.unffolow, name='unfollow'),
    path('<str:username>/', view=UserDetailView.as_view(), name='detail'),
    path('<str:username>/edit', view=UserUpdateView.as_view(), name='changeDetails'),
]

blog/models.py
from string import ascii_lowercase, digits

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.core.files.uploadedfile import InMemoryUploadedFile
from hashid_field import HashidAutoField
from PIL import Image
import sys
from io import BytesIO
from django.contrib.contenttypes.models import ContentType

IMG_SIZE = 2000, 2000
User = get_user_model()


class Post(models.Model):
    id = HashidAutoField(primary_key=True, alphabet=ascii_lowercase + digits)
    title = models.CharField(_('title'), max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('author'), related_name='authors')
    body = models.TextField(_('body'), blank=True)
    created_timestamp = models.DateTimeField(_('created timestamp'), auto_now_add=True)
    thumbnail = models.ImageField(default='mainBlog.png', upload_to='thumbnails/')

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.thumbnail != 'mainBlog.png':
            im = Image.open(self.thumbnail)
            output = BytesIO()
            im.resize(IMG_SIZE)
            im.save(output, format='JPEG', quality=50)
            output.seek(0)
            self.thumbnail = InMemoryUploadedFile(output, 'ImageField', f"{self.thumbnail.name.split('.')[0]}.jpg",
                                                  'image/jpeg',
                                                  sys.getsizeof(output), None)

        super().save(force_insert, force_update, using, update_fields)

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.id})

    def is_author(self, user: User):
        return user == self.author

    class Meta:
        ordering = ('-created_timestamp',)

    def __str__(self):
        return f'{self.title}'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name=_('post'), related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('author'), related_name='comments')
    body = models.TextField(_('body'))
    created_timestamp = models.DateTimeField(_('created timestamp'), auto_now_add=True)
    parent = models.ForeignKey('self', null=True, related_name='replies', on_delete=models.CASCADE, blank=True)

    class Meta:
        ordering = ('-created_timestamp',)

    def __str__(self):
        return f'Comment #{self.id} by {self.author} for {self.post}'

    def children(self):
        return Comment.objects.filter(parent=self)

    @property
    def is_parent(self):
        return False if self.parent is not None else True

blog/forms.py
from django import forms
from .models import Post, Comment


class PostUpload(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('thumbnail', 'title', 'body')


class CommentForm(forms.Form):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    parent_id = forms.IntegerField(widget=forms.HiddenInput, required=False)
    content = forms.IntegerField(widget=forms.Textarea)


class ReplyToComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ()

blog/views.py
from platform import python_version
from django import get_version as django_version
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, DetailView, ListView, TemplateView, UpdateView, DeleteView
from django.views.generic.edit import ModelFormMixin
import requests
from blog.models import Post, Comment
from users.models import User


class LandingView(TemplateView):
    template_name = 'blog/landing.html'


class HomeView(ListView):
    template_name = 'blog/home.html'
    model = Post
    context_object_name = 'posts'
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['active'] = 'blog-home'
        return context


class InfoView(TemplateView):
    template_name = 'blog/info.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context.update({
            'active': 'blog-info',
            'python_version': python_version(),
            'django_version': django_version(),
            'number_of_users': User.objects.count(),
            'number_of_posts': Post.objects.count(),
            'number_of_comments': Comment.objects.count(),
        })
        return context


class PostDisplay(ModelFormMixin, DetailView):
    template_name = 'blog/post_detail.html'
    model = Post
    fields = ('body',)

    def form_valid(self, form):
        return super().form_valid(form)

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.order_by('created_timestamp')
        return qs


class PostComment(CreateView):
    template_name = 'blog/post_detail.html'
    model = Comment
    fields = ('body', 'parent')

    def post(self, request, *args, **kwargs):
        print(self.request.POST.get('parent_id'))
        self.post_obj = Post.objects.get(pk=self.kwargs.get(self.pk_url_kwarg))
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        form.parent_id = self.request.POST.get('parent_id')
        parent_obj = None
        if form.parent_id:
            parent_qs = Comment.objects.filter(id=form.parent_id)
            if parent_qs.exists():
                parent_obj = parent_qs.first()
        form.instance.parent = parent_obj
        form.instance.post = self.post_obj
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = self.post_obj
        return context

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.post_obj.pk})


class PostChildComment(CreateView):
    model = Comment
    fields = ('body', 'parent')
    template_name = 'blog/reply_comment.html'


class PostDetailView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        view = PostDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = PostComment.as_view()
        return view(request, *args, **kwargs)


class TextPostCreateView(LoginRequiredMixin, CreateView):
    template_name = 'blog/post_create.html'
    model = Post
    fields = ('title', 'body', 'thumbnail')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'blog/post_update.html'
    fields = ('title', 'body', 'thumbnail')
    context_object_name = 'blog_post'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        return self.get_object().is_author(self.request.user) or self.request.user.is_superuser


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = 'blog/post_confirm_delete.html'
    model = Post
    context_object_name = 'post'
    success_url = reverse_lazy('blog:home')

    def test_func(self):
        return self.get_object().is_author(self.request.user) or self.request.user.is_superuser


class MakeSpecialPost(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/post_create_special.html'
    fields = ('title', 'body', 'thumbnail')

    context_object_name = 'blog_post'

    def get_chuck_jokes(self):
        url = 'https://api.chucknorris.io/jokes/random'
        response = requests.get(url).json()
        if response:
            quote = response.get('value')
            title = " ".join(quote.split()[:3])
        else:
            quote = 'The difference between something good and something great is attention to detail.'
            title = 'Charles'
        return title, quote

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_initial(self):
        title, quote = self.get_chuck_jokes()
        return {
            'title': title,
            'body': quote
        }

    def test_func(self):
        return self.get_object().is_author(self.request.user) or self.request.user.is_superuser

templates/blog/home.html
{% extends "base.html" %}
{% load i18n humanize %}

{% block content %}
    {% if user.is_staff  %}
        <div class="level">
            <div class="level-left"></div>
            <div class="level-right">
                <form method="POST" enctype="multipart/form-data">
                    <a href="{% url 'blog:post_create'  %}" type="submit" role="button" id="addContent"
                    > Add
                        content </a>
                </form>
            </div>
        </div>
    {% endif  %}
    <div class="column is-four-fifths">
        {% if user.is_authenticated %}
            <div class="level">
                <div class="level-left has-margin-b-md">
                    <div class="level-item">
                        <a class="button is-info is-outlined" href="{% url 'blog:text_post_create' %}">
                            <span class="icon is-medium"><i class="fas fa-edit"></i></span>
                            <span>{% trans "New Text Post" %}</span>
                        </a>
                    </div>
                </div>
                <div class="level-right has-margin-b-md">
                    <div class="level-item">
                        <div class="field">
                            <em>{% trans "Built with Django" %}</em>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="has-text-grey-light has-text-weight-semibold is-uppercase">
            {% trans "Recent posts" %}
        </div>
        <hr/>
        {% for post in posts %}
            <div class="has-margin-b-lg">
                {% if post.thumbnail %}
                    <a class="has-text-dark" href="{{ post.get_absolute_url }}">
                        <figure class="is-marginless">
                            <img class="is-128x128" src="{{ post.thumbnail.url }}">
                        </figure>
                    </a>
                {% endif %}
                <h4 class="title is-4 is-marginless">
                    <a class="has-text-dark" href="{{ post.get_absolute_url }}">{{ post.title|truncatechars:50 }}</a>
                </h4>
                <div class="has-text-grey has-margin-b-sm">
                    {% blocktrans with url=post.author.get_absolute_url username=post.author.username|truncatechars:50 %}
                        Posted by <a href="{{ url }}">{{ username }}</a>
                    {% endblocktrans %}
                    {{ post.created_timestamp|naturaltime }}
                </div>
                {% if post.image %}
                    <figure class="image is-square">
                        <img src="{{ post.image.url }}">
                    </figure>
                {% endif %}
                <p>{{ post.body|truncatechars:200 }}</p>
            </div>
        {% empty %}
            <div>{% trans "There are no posts yet" %} 😕</div>
        {% endfor %}
        {% include 'pagination.html' %}
    </div>
{% endblock %}

templates/blog/info.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="has-margin-b-lg">
        <h4 class="title is-4">
            {% blocktrans %}
                Find the task description
                <a href="https://ained.ttu.ee/course/view.php?id=193#section-17">here</a>.
            {% endblocktrans %}
        </h4>
    </div>
{% endblock %}

{% block extra_content %}
    <section class="hero is-light is-bold">
        <div class="hero-body">
            <div class="container">
                <nav class="level">
                    <div class="level-item has-text-centered">
                        <div>
                            <p class="heading">{% trans "Total Users" %}</p>
                            <p class="title">{{ number_of_users }}</p>
                        </div>
                    </div>
                    <div class="level-item has-text-centered">
                        <div>
                            <p class="heading">{% trans "Total Posts" %}</p>
                            <p class="title">{{ number_of_posts }}</p>
                        </div>
                    </div>
                    <div class="level-item has-text-centered">
                        <div>
                            <p class="heading">{% trans "Total Comments" %}</p>
                            <p class="title">{{ number_of_comments }}</p>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="columns is-mobile is-centered">
            <div class="field is-grouped is-grouped-multiline">
                <div class="control">
                    <div class="tags has-addons">
                        <span class="tag is-dark">{% trans "django" %}</span>
                        <span class="tag is-info">{{ django_version }}</span>
                    </div>
                </div>
                <div class="control">
                    <div class="tags has-addons">
                        <span class="tag is-dark">{% trans "python" %}</span>
                        <span class="tag is-info">{{ python_version }}</span>
                    </div>
                </div>
                <div class="control">
                    <div class="tags has-addons">
                        <span class="tag is-dark">{% trans "chat" %}</span>
                        <span class="tag has-addons is-info">
                            <a href="https://discord.gg/A7BjPrj">
                                <i class="fab fa-lg fa-discord has-text-white"></i>
                            </a>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/blog/landing.html
{% extends 'base.html' %}
{% load i18n humanize %}
{% block content %}
    <section class="hero landing__image">
        <div class="hero-body">
            <div class="container">
                <h1 class="title has-padding-b-lg is-1 white_important">
                    Hey, There!
                </h1>
                <h2 class="subtitle is-1 has-text-right white_important">
                    We have been waiting for you!!!
                </h2>

            </div>
            <div class="tile is-parent is-4 has-margin-t-lg has-margin-b-lg">
                <p class="has-text-left subtitle white_important has-text-weight-semibold special">
                    A customizable reading experience, made just for you.
                    With the power of the network, different ways to engage with stories, and the ability to follow
                    your
                    favorite
                    topics, writers, and publications, you’re in control of your reading experience. So the stories
                    that
                    matter
                    most to
                    you are always at your fingertips.
                </p>
            </div>
            <div class="tile is-ancestor has-margin-t-lg">
                <div class="tile is-parent is-6">
                    <img src="" alt="">
                </div>

            </div>
            <div class="level has-text-centered has-margin-t-lg" style="justify-content: center">
                <a href="{% url 'account_login' %}" class="button is-primary is-large">
                    <span class="icon"><i class="fa fa-sign-in-alt"></i></span>
                    <span>{% trans "Sign Up Now" %}</span>
                </a>
            </div>
        </div>
    </section>

    <section class="section has-margin-t-lg">

        <nav class="level is-mobile">
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Follow us on instagram</p>
                    <a href="https://www.instagram.com/python.coders/" target="_blank">
                        <span class="icon"><i class="fab fa-instagram fa-lg"></i></span>
                    </a>

                </div>
            </div>
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Made with Bulma</p>
                    <a href="https://bulma.io/" target="_blank">
                        <img style="width: 35%" class="is-128x128"
                             src="https://bulma.io/images/made-with-bulma--dark.png"
                             alt="Bulma">
                    </a>
                </div>
            </div>
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Users</p>
                    <p class="title">45</p>
                </div>
            </div>
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Posts</p>
                    <p class="title">789</p>
                </div>
            </div>
        </nav>
    </section>


{% endblock %}


{% block extra_content %}

{% endblock %}

templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="column is-8 is-offset-2">
        <div class="box has-box-shadow">
            <div class="notification is-danger">
                {% trans "Are you sure you want to delete this post?" %}
            </div>
            <form method="post" action="">
                {% csrf_token %}
                <div class="has-text-centered">
                    <button class="button is-danger is-outlined" type="submit">
                        {% trans "Confirm" %}
                    </button>
                    <a href="{{ post.get_absolute_url }}" class="button is-info" type="submit">
                        {% trans "Cancel" %}
                    </a>
                </div>
                <hr />
            </form>
        </div>
    </div>
{% endblock %}

templates/blog/post_create.html
{% extends "blog/post_create_base.html" %}
{% load i18n %}

{% block additional_fields %}
    <div class="field">
        <textarea name="body" class="textarea" placeholder="{% trans 'Write the post body here ...' %}" required></textarea>
        <div class="has-text-danger">{{ form.body.errors }}</div>
    </div>
{% endblock %}

templates/blog/post_create_base.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="column is-8 is-offset-2">
        <div class="box has-box-shadow">
            <h1 class="title">{% trans "New Post" %}</h1>
            <form method="post" action="" enctype="multipart/form-data" {% block form_attrs %}{% endblock %}>
                {% csrf_token %}
                {% if form.non_field_errors %}
                    <div class="notification is-danger">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
                <div class="field">
                    <p class="control has-icons-left">
                        <input name="title" class="input" type="text" placeholder="Title" autofocus required>
                        <span class="icon is-small is-left"><i class="fas fa-heading"></i></span>
                    </p>
                    <div class="has-text-danger">{{ form.title.errors }}</div>
                </div>
                <div class="field">
                    <p class="control has-icons-left">
                        {{ form.thumbnail }}
                    </p>
                    <div class="has-text-danger">{{ form.title.errors }}</div>
                </div>
                {% block additional_fields %}{% endblock %}
                <button class="button is-primary" type="submit">{% trans "Create" %}</button>
                <hr/>
            </form>
        </div>
    </div>
{% endblock %}

templates/blog/post_detail.html
{% extends "base.html" %}
{% load i18n humanize %}

{% block content %}
    <div class="column is-four-fifths">
        <h2 class="title is-2">{{ post.title }}</h2>
        {% if user == post.author or user.is_superuser %}
            <div class="level has-margin-t-md">
                <div class="level-left">
                    <a href="{% url 'blog:post_update' post.pk %}" class="level-item button is-small is-dark">
                        <span class="icon is-small"><i class="fas fa-edit"></i></span>
                        <span>{% trans "Edit" %}</span>
                    </a>
                    <a href="{% url 'blog:post_delete' post.pk %}" class="level-item button is-small is-danger">
                        <span class="icon is-small"><i class="fas fa-times"></i></span>
                        <span>{% trans "Delete" %}</span>
                    </a>
                </div>
                <div class="level-right">
                    <figure class="">
                        <img class="is-128x128" src="{{ post.thumbnail.url }}" height="100" width="100">
                    </figure>
                </div>
            </div>
        {% endif %}
        <hr/>
        <div class="box">{{ post.body|linebreaksbr|truncatechars:1000 }}</div>
        <hr/>
        <form method="post" action="" class="has-margin-b-lg">
            {% csrf_token %}
            <article class="media has-margin-t-lg">
                <figure class="media-left">
                    <p class="image is-64x64">
                        <img src="{{ user.avatar.url }}">
                    </p>
                </figure>
                <div class="media-content">
                    <div class="field">
                        <p class="control">
                            <textarea name="body" class="textarea" placeholder="{% trans 'Add a comment...' %}"
                                      required></textarea>
                        </p>
                    </div>
                    <div class="has-text-danger">{{ form.body.errors }}</div>
                    <nav class="level">
                        <div class="level-left">
                            <div class="level-item">
                                <button class="button is-info" type="submit">{% trans "Submit" %}</button>
                            </div>
                        </div>
                    </nav>
                </div>
            </article>
        </form>

        {% for comment in post.comments.all %}
            {% if comment.parent is None %}
                <article class="media">
                <figure class="media-left">
                    <p class="image is-64x64">
                        <img src="{{ comment.author.avatar.url }}">
                    </p>
                </figure>
                <div class="media-content">
                <div class="content">
                    <p>
                        <strong>{{ comment.author.name }}</strong>
                        <small>
                            <a
                                class="has-text-grey"
                                href="{% url 'users:detail' comment.author.username %}">{{ comment.author.username }}
                            </a>
                        </small>
                        <small>{{ comment.created_timestamp|naturaltime }}</small>
                        <br>
                        <span>{{ comment.body|truncatechars:255 }}</span>
                    </p>
                </div>
                {% for child_comment in comment.children %}
                    <article class="media">
                        <figure class="media-left">
                            <p class="image is-64x64">
                                <img src="{{ child_comment.author.avatar.url }}">
                            </p>
                        </figure>
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <strong>{{ child_comment.author.name }}</strong>
                                    <small>
                                        <a
                                            class="has-text-grey"
                                            href="{% url 'users:detail' child_comment.author.username %}">{{ child_comment.author.username }}
                                        </a>
                                    </small>
                                    <small>{{ child_comment.created_timestamp|naturaltime }}</small>
                                    <br>
                                    <span>{{ child_comment.body|truncatechars:255 }}</span>
                                </p>
                            </div>
                        </div>
                    </article>

                {% endfor %}
                <form method="post" action="" class="has-margin-b-lg is-hidden" id="replyToComment">
                    {% csrf_token %}
                    <article class="media has-margin-t-lg">
                        <figure class="media-left">
                            <p class="image is-64x64">
                                <img src="{{ user.avatar.url }}">
                            </p>
                        </figure>
                        <div class="media-content">
                            <div class="field">
                                <p class="control">
                            <textarea name="body" class="textarea" placeholder="{% trans 'Add a comment...' %}"
                                      required></textarea>
                                </p>
                            </div>
                            <div class="has-text-danger">{{ form.body.errors }}</div>
                            <input type="hidden" name="parent_id" value="{{ comment.id }}">

                            <nav class="level">
                                <div class="level-left">
                                    <div class="level-item">
                                        <button class="button is-info" type="submit">{% trans "Submit" %}</button>
                                    </div>
                                </div>
                            </nav>
                        </div>
                    </article>
                </form>
                <nav class="level is-mobile has-margin-t-lg">
                    <div class="level-left">
                        <a class="level-item">
                            <span id="replyButton" class="icon is-small"><i class="fas fa-reply"></i></span>
                        </a>
                    </div>
                </nav>
            {% endif %}




        </div>
        </article>
        {% empty %}
            <div class="has-text-weight-light has-text-centered">{% trans "No comments yet." %}</div>

        {% endfor %}
    </div>
{% endblock %}

templates/blog/reply_comment.html
{% extends "base.html" %}
{% load i18n humanize %}

{% block additional_fields %}
    {% for child_comment in comment.children %}
        <article class="media">
            <figure class="media-left">
                <p class="image is-64x64">
                    <img src="{{ child_comment.author.avatar.url }}">
                </p>
            </figure>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>{{ child_comment.author.name }}</strong>
                        <small>
                            <a
                                class="has-text-grey"
                                href="{% url 'users:detail' child_comment.author.username %}">{{ child_comment.author.username }}
                            </a>
                        </small>
                        <small>{{ child_comment.created_timestamp|naturaltime }}</small>
                        <br>
                        <span>{{ child_comment.body|truncatechars:255 }}</span>
                    </p>
                </div>
            </div>
        </article>

    {% endfor %}
{% endblock %}