blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.LandingView.as_view(), name='landing_page'),
    path('blog/', views.HomeView.as_view(), name='home'),
    path('info/', views.InfoView.as_view(), name='info'),
    path('post/create-text/', views.TextPostCreateView.as_view(), name='text_post_create'),
    path('post_create_special/', views.MakeSpecialPost.as_view(), name='post_create'),
    path('post/<pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<pk>/<comment_id>/reply/', views.PostChildComment.as_view(), name='replyToComment'),
    path('post/<pk>/update', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<pk>/delete', views.PostDeleteView.as_view(), name='post_delete'),
]

dj02_django_blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dj02_django_blog import settings

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),

    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import UserDetailView, UserListView, UserRedirectView, UserUpdateView, add_follower
from . import views

app_name = 'users'

urlpatterns = [
    path('', view=UserListView.as_view(), name='list'),
    path('~redirect/', view=UserRedirectView.as_view(), name='redirect'),
    path('<str:username>/follow/', views.add_follower, name='follow'),
    path('<str:username>/unfollow/', views.unffolow, name='unfollow'),
    path('<str:username>/', view=UserDetailView.as_view(), name='detail'),
    path('<str:username>/edit', view=UserUpdateView.as_view(), name='changeDetails'),
]

templates/base.html
{% load i18n static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% trans "Django Blog" %}{% endblock %}</title>
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
    <link rel="stylesheet" href="{% static "css/bulma.css" %}">
    <link rel="stylesheet" href="{% static "css/spacing.css" %}">
    <link rel="stylesheet" href="{% static "css/project.css" %}">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>
<section class="hero is-dark">
    <div class="hero-head">
        <nav class="navbar">
            <div class="navbar-brand">
                <a class="navbar-item" href="{% url 'blog:home' %}"><i class="fas fa-code"></i> </a> <a
                role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
                data-target="mainNavbar" id="navBurger"> <span aria-hidden="true"></span> <span
                aria-hidden="true"></span> <span aria-hidden="true"></span> </a>
            </div>
            <div id="mainNavbar" class="navbar-menu">
                <div class="navbar-end">
                    <a class="navbar-item {% if active == 'blog-home' %}is-active{% endif %}"
                       href="{% url 'blog:home' %}">{% trans "Blog" %}
                    </a> <a class="navbar-item {% if active == 'user-list' %}is-active{% endif %}"
                            href="{% url 'users:list' %}">{% trans "Users" %}
                </a> <a class="navbar-item {% if active == 'blog-info' %}is-active{% endif %}"
                        href="{% url 'blog:info' %}">{% trans "Info" %}
                </a>
                    {% if user.is_staff %}
                        <a class="navbar-item has-text-warning" href="{% url 'admin:index' %}">{% trans "Admin" %}
                        </a>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <span class="navbar-item ">
                            <a class="has-text-success {% if active == 'user-detail' %}is-active{% endif %}"
                               href="{% url 'users:detail' user.username %}">{{ user.username }}
                            </a>
                        </span>
                        <span class="navbar-item">
                            <a href="{% url 'account_logout' %}" class="button is-primary is-outlined">
                                <span class="icon"><i class="fa fa-sign-out-alt"></i></span>
                                <span>{% trans "Logout" %}</span>
                            </a>
                        </span>
                    {% else %}
                        <span class="navbar-item">
                            <a href="{% url 'account_login' %}" class="button is-primary is-outlined">
                                <span class="icon"><i class="fa fa-sign-in-alt"></i></span>
                                <span>{% trans "Login" %}</span>
                            </a>
                        </span>
                    {% endif %}
                </div>
            </div>
        </nav>
    </div>
</section>
<section class="section">
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</section>
{% block extra_content %}{% endblock %}
<footer class="footer">
    <div class="is-flex aligned is-justified-center">

        <span>  Made with <span class="icon">
            <a href="https://www.python.org/" target="_blank">
                <i class="fab fa-python"></i>
            </a>
        </span>
            With a special help from <a href="https://www.djangoproject.com/" target="_blank">django</a>.</span>


    </div>
</footer>
<script src="{% static 'js/main.js' %}"></script>

{% block scripts %}{% endblock %}
</body>
</html>

templates/pagination.html
{% load i18n %}

{% if is_paginated %}
    <nav class="pagination is-centered">
        {% if page_obj.has_previous %}
            <a
                class="pagination-previous"
                href="?page={{ page_obj.previous_page_number|stringformat:'d' }}{{ getvars }}{{ hashtag }}"
            >
                {% trans "Previous" %}
            </a>
        {% else %}
            <a class="pagination-previous" disabled>{% trans "Previous" %}</a>
        {% endif %}

        {% if page_obj.has_next %}
            <a
                class="pagination-next"
                href="?page={{ page_obj.next_page_number|stringformat:'d' }}{{ getvars }}{{ hashtag }}"
            >
                {% trans "Next" %}
            </a>
        {% else %}
            <a class="pagination-next" disabled>{% trans "Next" %}</a>
        {% endif %}

        <ul class="pagination-list">
            {% for page in paginator.page_range %}
                <li>
                    <a
                        class="pagination-link{% ifequal page page_obj.number %} is-current{% endifequal %}"
                        href="?page={{ page|stringformat:"d" }}{{ getvars }}{{ hashtag }}"
                    >
                        {{ page|stringformat:'d' }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </nav>
{% endif %}