blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.LandingView.as_view(), name='landing_page'),
    path('blog/', views.HomeView.as_view(), name='home'),
    path('info/', views.InfoView.as_view(), name='info'),
    path('post/create-text/', views.TextPostCreateView.as_view(), name='text_post_create'),
    path('post_create_special/', views.MakeSpecialPost.as_view(), name='post_create'),
    path('post/<pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<pk>/<comment_id>/reply/', views.PostChildComment.as_view(), name='replyToComment'),
    path('post/<pk>/update', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<pk>/delete', views.PostDeleteView.as_view(), name='post_delete'),
]

dj02_django_blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dj02_django_blog import settings

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),

    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import UserDetailView, UserListView, UserRedirectView, UserUpdateView, add_follower
from . import views

app_name = 'users'

urlpatterns = [
    path('', view=UserListView.as_view(), name='list'),
    path('~redirect/', view=UserRedirectView.as_view(), name='redirect'),
    path('<str:username>/follow/', views.add_follower, name='follow'),
    path('<str:username>/unfollow/', views.unffolow, name='unfollow'),
    path('<str:username>/', view=UserDetailView.as_view(), name='detail'),
    path('<str:username>/edit', view=UserUpdateView.as_view(), name='changeDetails'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.dispatch import receiver
from django.urls import reverse
from django.core.validators import URLValidator
from django.utils.translation import ugettext_lazy as _
from allauth.socialaccount.models import SocialAccount
from allauth.account.signals import user_signed_up


class User(AbstractUser):
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    avatar_url = models.TextField(
        _('Avatar of the github user'), blank=True, validators=[URLValidator])
    avatar = models.ImageField(default='default.png', upload_to='avatars/')
    follows = models.ManyToManyField('User', related_name='followed_by')

    @property
    def get_full_name(self):
        return super().get_full_name()

    def get_short_name(self):
        return super().get_short_name()

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    def __str__(self):
        return f'{self.username}'


@receiver(user_signed_up)
def social_login_profilepic(sociallogin, user, **kwargs):
    picture_url = ''
    if sociallogin:
        if sociallogin.account.provider == 'github':
            picture_url = sociallogin.account.get_avatar_url()
    user.avatar_url = picture_url
    user.save()

users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):
    error_message = forms.UserCreationForm.error_messages.update(
        {'duplicate_username': _('This username has already been taken.')}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data['username']

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages['duplicate_username'])

users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models.functions import Lower
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from blog.models import Comment, Post

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'users/detail.html'
    context_object_name = 'blog_user'
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['active'] = 'user-detail'
        context['nr_of_posts'] = Post.objects.filter(author=self.object).count()
        context['blog_posts'] = Post.objects.filter(author=self.object)
        context['nr_of_comments'] = Comment.objects.filter(author=self.object).count()
        return context


class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'users/changeDetails.html'
    fields = ('username', 'avatar')
    context_object_name = 'blog_user'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    permission_denied_message = 'Hey Mate! No cookie for you!'

    def test_func(self):
        obj = self.get_object()
        return obj == self.request.user


class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'users/list.html'
    context_object_name = 'blog_users'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    paginate_by = 5

    def get_queryset(self):
        return super().get_queryset().order_by(Lower('username'))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['active'] = 'user-list'
        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail', kwargs={'username': self.request.user.username})


def add_follower(request, username):
    to_follow = User.objects.filter(username=username).first()
    if request.user != to_follow:
        logged_in_user = User.objects.filter(username=request.user).first()
        logged_in_user.follows.add(to_follow)
        to_follow.save()
        logged_in_user.save()

    return render(request, 'users/follow.html')


def unffolow(request, username):
    to_follow = User.objects.filter(username=username).first()
    if request.user != to_follow:
        request.user.follows.remove(to_follow)
        to_follow.save()
        request.user.save()
    else:
        messages.error(request, 'You are not allowed to do that.')

    return render(request, 'users/unfollow.html', {'user': to_follow})

templates/users/changeDetails.html
{% extends "base.html" %}{% load static i18n %}
{% block title %}{% trans "User" %}: {{ blog_user.username }}{% endblock %}
{% block content %}

    <section class="tile is-ancestor is-vertical">
        <form method="post" enctype="multipart/form-data" class="empty-form">
            {% csrf_token %}
            <div class="tile is-parent">
                <article class="tile is-child notification is-white">
                    <div class="level">
                        <div class="level-left">
                            <p class="title">{{ user.username }}</p>
                        </div>
                        <div class="level-right">
                            <figure class="image is-128x128">
                                <img src="{{ user.avatar.url }}" alt="avatar" class="is-rounded" height="300"
                                     width="300">
                            </figure>
                        </div>
                    </div>
                    <p class="subtitle">Would you like to change details about yourself?</p>
                    <div class="field ">
                        <p class="control has-icons-left">
                            {{ form.avatar }}
                        </p>
                        <div class="has-text-danger">{{ form.username.errors }}</div>
                    </div>
                    <h5 class="has-margin-b-lg">Username:</h5>
                    <div class="field ">
                        <p class="control has-icons-left">
                            <input name="username" class="input" type="text" placeholder="{{ user.username }}" autofocus
                                   required value="{{ user.username }}">
                            <span
                                class="icon is-small is-left"><i class="fas fa-user"></i></span>
                        </p>
                        <div class="has-text-danger">{{ form.username.errors }}</div>
                    </div>
                    <div class="level">
                        <div class="level-left"></div>
                        <div class="level-right">
                            <input type="submit" class="button is-link" value="{% trans "Submit" %}">
                        </div>
                    </div>
                </article>
            </div>
        </form>
        <h1>

        </h1>


    </section>

{% endblock content  %}

templates/users/detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}{% trans "User" %}: {{ blog_user.username }}{% endblock %}

{% block content %}
    <div class="columns has-margin-b-lg">
        <div class="column has-margin-b-lg">
            <figure class="media">
                <p class="image is-128x128">
                    {% if blog_user.avatar_url %}
                        <img class="is-rounded" src="{{ blog_user.avatar_url }}">
                    {% else %}
                        <img class="is-rounded" src="{{ blog_user.avatar.url }}">
                    {% endif %}
                </p>
            </figure>
            {% if blog_user.username %}
                <h5 class="title is-5">{{ blog_user.username }}</h5>
            {% endif %}
            {% if blog_user.name %}
                <h6 class="subtitle is-6 title">{{ blog_user.name }}</h6>
            {% endif %}
        </div>
        <div class="column">
            {% if blog_user.username == user.username %}
                <div class="container">
                    <p><span class="title">{{ blog_user.username }}</span>, Would you like to change your information?
                    </p>
                    <a class="button is-info"
                       href="{% url 'users:changeDetails' blog_user.username %}">{% trans "Change Details" %}</a>
                </div>
            {% endif %}
        </div>

    </div>

    {% if nr_of_posts %}
        <hr>
        <h1 class="title">Here are {{ blog_user.username }} Recent Posts.</h1>
        <hr>
        <section class="section">
            <div class="tile is-ancestor" style="flex-wrap: wrap">
                {% for blog_post in blog_posts %}
                    <div class="tile is-parent is-4">
                        <article class="tile is-child box">
                            <h4 class="title is-4 has-margin-md">
                                <a class="has-text-dark"
                                   href="{{ blog_post.get_absolute_url }}">{{ blog_post.title|truncatechars:50 }}</a>
                            </h4>
                            <p class="has-margin-md">
                                {{ blog_post.body|truncatechars:50 }}
                            </p>
                            {% if blog_post.thumbnail %}
                                <a class="has-text-dark" href="{{ blog_post.get_absolute_url }}">
                                    <figure class="is-marginless">
                                        <img class="is-128x128" src="{{ blog_post.thumbnail.url }}">
                                    </figure>
                                </a>
                            {% endif %}
                        </article>

                    </div>
                {% endfor %}
            </div>
        </section>
    {% endif %}


{% endblock content %}

{% block extra_content %}
    <hr/>
    <section class="hero is-bold">
        <div class="hero-body">
            <div class="container">
                <nav class="level">
                    <div class="level-item has-text-centered">
                        <div>
                            <p class="heading">{% trans "Followers" %}</p>
                            <p class="title">
                                {{ blog_user.followed_by.count }}
                            </p>
                        </div>
                    </div>
                    <div class="level-item has-text-centered">
                        <div>
                            <p class="heading">{% trans "Posts" %}</p>
                            <p class="title">{{ nr_of_posts }}</p>
                        </div>
                    </div>
                    <div class="level-item has-text-centered">
                        <div>
                            <p class="heading">{% trans "Comments" %}</p>
                            <p class="title">{{ nr_of_comments }}</p>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </section>
{% endblock %}

templates/users/follow.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Django Blog | Users" %}{% endblock %}

{% block content %}
    <div class="column is-8 is-offset-2">

        <div class="card has-box-shadow">
            <h1 class="title">You successfully unfollowed: <span class="has-text-success">{{ user }}</span></h1>
            <div class="level-right">
                <a class="button is-dark is-large" href="{% url 'users:list' %}">
                    Go Back
                </a>
            </div>
        </div>
    </div>
{% endblock content %}

templates/users/list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Django Blog | Users" %}{% endblock %}

{% block content %}
    <div class="column is-8 is-offset-2">
        <div class="card has-box-shadow">
            <div class="has-background-info has-padding-none has-margin-none">
                <h1 class="title is-3 has-padding-md has-background-grey has-text-white">
                    <span>{% trans "Users List" %}</span>
                </h1>
            </div>

            <div class="has-padding-lg">
                {% for blog_user in blog_users %}
                    <div class="level">
                        <div class="level-left">
                            <div>
                                <figure class="image is-rounded is-64x64">
                                    {% if blog_user.avatar_url %}
                                        <img class="is-rounded" src="{{ blog_user.avatar_url }}">
                                    {% else %}
                                        <img class="is-rounded" src="{{ blog_user.avatar.url }}">
                                    {% endif %}
                                </figure>
                            </div>
                            <div class="has-text-grey has-margin-l-lg">
                                {% if blog_user.username == user.username %}
                                    <a
                                        class="is-active has-text-success"
                                        href="{% url 'users:detail' blog_user.username %}">{{ blog_user.username }}
                                    </a>
                                {% else %}
                                    <a
                                        class="has-text-grey"
                                        href="{% url 'users:detail' blog_user.username %}">{{ blog_user.username }}
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="level-right">
                            <a class="button is-primary is-rounded is-small"
                               href="{% url 'users:follow'  blog_user.username %}">

                                <span class="icon is-small">
                                  <i class="fas fa-heart"></i>
                                    {% if blog_user in user.follows.all %}
                                        </span>{% trans "Following" %}<span>
                                         <a class="button is-warning is-rounded is-small"
                                            href="{% url 'users:unfollow'  blog_user.username %}">
                                        <span class="icon is-small">
                                         <i class="fas fa-exclamation-circle"></i>
                                                </span>{% trans "UnFollow" %}<span>
                                        </span>
                                        </a>
                                        {% elif user.username == blog_user.username %}
                                         </span>{% trans "You" %}<span>
                                        {% else %}
                                            </span>{% trans "Follow" %}<span>
                                    {% endif %}
                                    </span>
                            </a>

                        </div>
                    </div>
                {% endfor %}
                {% include 'pagination.html' %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/users/unfollow.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Django Blog | Users" %}{% endblock %}

{% block content %}
    <div class="column is-8 is-offset-2">
        <div class="card has-box-shadow">
            <h1 class="title">You successfully unfollowed: <span class="has-text-success">{{ user }}</span></h1>
            <div class="level-right">
                <a class="button is-dark is-large" href="{% url 'users:list' %}">
                    Go Back
                </a>
            </div>
        </div>
    </div>
{% endblock content %}